### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by isayeter** [kootenpv/access_points#23]
Please provide the output of the error below this line at github.com/kootenpv/access_points/issues
list index out of range
Line:
           SUPERONLINE_WiFi_57A5                   -67  36      Y  -- WPA(PSK/AES,TKIP/TKIP) RSN(PSK/AES,TKIP/TKIP)

**Comment by kootenpv** [comment]
What OS was this?

**Comment by isayeter** [comment]
Hello @kootenpv , it's MacOS Monterey (12.3.1) on M1 Max

**Comment by athen66** [comment]
Still happening, MacOS Monterey 12.6.

**Comment by kootenpv** [comment]
Would very much welcome someone to try to solve this in  PR

**Comment by NISH1001** [comment]
@athen66 @kootenpv So, I encountered this repo while randomly fiddling with tools. Apparently, the access_points binary gives correct `List[dict]` if ran as an external script (for instance copy the __init__.py somewhere and run it..it gives correct output). But doesn't work while being under miniconda/anaconda env.

**Comment by kootenpv** [comment]
> @athen66 @kootenpv So, I encountered this repo while randomly fiddling with tools. Apparently, the access_points binary gives correct `List[dict]` if ran as an external script (for instance copy the **init**.py somewhere and run it..it gives correct output). But doesn't work while being under miniconda/anaconda env.
> 
> Note: I tested this on MacOS Monterey 12.6 itself. The actual python script does give correct list. Maybe it's because of permission issue.

Wow thanks for figuring that out. Not sure if there is anything we can do other than recommend running as root?

**Comment by NISH1001** [comment]
I think one way for this to work is by describing how we can add the `access_points` module to `$PYTHONPATH` env. I will try to figure out a better way for this over the weekend (if I have time). Otherwise, I have manually added the module to sys.path in `whereami` module to enforce.
 
Anyway, thanks for such a nice tool. I liked the idea of just using barebone access point names and training to the random forest.

**Comment by michaeljoseph** [comment]
@kootenpv I think this needs a new pypi release? I think this issue was fixed in #22, but the last release was in 2019.

**Comment by kootenpv** [comment]
@michaeljoseph thanks - I guess I had not read output of deploy script earlier.

0.4.73 is available - please confirm this fixes for you

**Comment by michaeljoseph** [comment]
```
🕙 2022-12-22 12:48:15  ❯ poetry add access_points
Using version ^0.4.73 for access-points

Updating dependencies
Resolving dependencies... (1.5s)

Writing lock file

Package operations: 0 installs, 1 update, 0 removals

  • Updating access-points (0.4.66 -> 0.4.73)

🕙 2022-12-22 12:49:27  ✖  poetry run access_points
[{"ssid": "dlink-956M-2.4G-8e0e", "bssid": "", "quality": 18, "security": "WPA(PSK/AES/AES) RSN(PSK/AES/AES) "}, {"ssid": "Scotties", "bssid": "", "quality": 20, "security": "WPA(PSK/AES/AES) RSN(PSK/AES/AES) "}, {"ssid": "Cedars-5G", "bssid": "", "quality": 30, "security": "WPA(PSK/AES/AES) RSN(PSK/AES/AES) "}, {"ssid": "Cedars Halfway_5G", "bssid": "", "quality": 28, "security": "WPA(PSK/AES/AES) RSN(PSK/AES/AES) "}, {"ssid": "Cedars Halfway", "bssid": "", "quality": 38, "security": "WPA(PSK/AES/AES) RSN(PSK/AES/AES) "}, {"ssid": "Cedars", "bssid": "", "quality": 52, "security": "WPA(PSK/AES/AES) RSN(PSK/AES/AES) "}, {"ssid": "Cedars", "bssid": "", "quality": 86, "security": "WPA(PSK/AES,TKIP/TKIP) RSN(PSK/AES,TKIP/TKIP) "}]
```

🙌 🥳 🙏🏼
