### ISSUE TITLE
Add Support for other NetworkManagers

### ISSUE THREAD

**Issue by DeastinY** [kootenpv/access_points#8]
I am using connmanctl and will look into creating a compatibility PR :)

**Comment by DeastinY** [comment]
iwlist was working good, so I just got a false detection as NM is installed, but not enabled.
https://github.com/kootenpv/access_points/pull/9 changes the detection to use `systemctl`

**Comment by kootenpv** [comment]
I noticed `nmcli` does not return all wifi when it is connected to a single one! I feel like I should drop it as the first choice :/ What was your reason for wanting to use `ncmli`?
